The following fails, as expected.

```scala repl:fail
sys.error("runtime failure")
```
