The following fails, but isn't expected to.

```scala repl
sys.error("runtime failure")
```
